{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "theone3-nginx.serviceAccountName" . }}
  labels:
{{ include "theone3-nginx.labels" . | indent 4 }}
{{- end -}}
